<a href="https://colab.research.google.com/github/SangminAhn21/DL_Study/blob/main/Deep_Learning_from_Scratch_2/Chapter1_Neural_Network_Review/210925.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(3, 2)
print(np.dot(a, b))
print(a @ b)

[[10 13]
 [28 40]]
[[10 13]
 [28 40]]


In [11]:
params = [1]
a = params
b, = params
print(a, b)

[1] 1


In [7]:
a = [1, 2, 3]
b = [4, 5, 6]
a = b
print(a is b)

True


In [15]:
a = np.arange(27).reshape(3, 3, 3)
print(a)
print(a[0, ...])
print(a[0, ..., 0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 3 6]


In [17]:
a = np.random.randn(3)
a.dtype

dtype('float64')